name: phantomjs-ijohnson
version: 2.1.1
summary: PhantomJS (phantomjs.org) is a headless WebKit scriptable with JavaScript
description: |
  PhantomJS is a headless WebKit scriptable with a JavaScript API. 
  It has fast and native support for various web standards: DOM handling, CSS selector, JSON, Canvas, and SVG.
confinement: strict
grade: stable

apps:
  phantomjs-ijohnson:
    command: 'bin/phantomjs'
    plugs: [network-bind, network]

parts:
  clang:
    plugin: nil
    build: |
        set -e
        wget -c http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-aarch64-linux-gnu.tar.xz
        tar -xf clang+llvm-3.8.0-aarch64-linux-gnu.tar.xz -C $SNAPCRAFT_STAGE
    build-packages: [wget]
  openssl:
    source: https://github.com/openssl/openssl.git
    source-type: git
    source-tag: OpenSSL_1_1_0g
    plugin: make
    build: |
      ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib ${OPENSSL_FLAGS} linux-generic64
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT depend
      sudo make install_sw
  icu:
    after: [openssl]
    source-type: svn
    source: http://source.icu-project.org/repos/icu/tags/release-55-1
    plugin: make
    build: |
      cd icu4c/source
      ./configure --prefix=/usr --enable-static --disable-shared
      make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
      sudo make install
  phantomjs:
    after: [clang]
    plugin: python
    source: https://github.com/ariya/phantomjs.git
    source-type: git
    source-tag: 2.1.1
    prepare: |
        git submodule init
        git submodule update
    build: |
        cd src
        export CLANG_DIR=$SNAPCRAFT_STAGE/clang+llvm-3.8.0-aarch64-linux-gnu/bin/
        export CC=$CLANG_DIR/clang
        export CXX=$CLANG_DIR/clang++
        python build.py  --confirm --release --qt-config="-no-pkg-config" --git-clean-qtbase --git-clean-qtwebkit
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        cp bin/phantomjs $SNAPCRAFT_PART_INSTALL/bin/phantomjs
    stage-packages:
      - build-essential
      - g++
      - flex
      - bison
      - gperf
      - ruby
      - perl
      - libsqlite3-dev
      - libfontconfig1-dev
      - libicu-dev
      - libfreetype6
      - libssl-dev 
      - libpng-dev
      - libjpeg-dev
      - python
      - libx11-dev
      - libxext-dev
