name: phantomjs-ijohnson
version: 2.1.1
summary: PhantomJS (phantomjs.org) is a headless WebKit scriptable with JavaScript
description: |
  PhantomJS is a headless WebKit scriptable with a JavaScript API. 
  It has fast and native support for various web standards: DOM handling, CSS selector, JSON, Canvas, and SVG.
confinement: strict
grade: stable

apps:
  phantomjs-ijohnson:
    command: 'bin/phantomjs'
    plugs: [network-bind, network]

parts:
  clang:
    plugin: nil
    build: |
        set -e
        wget -c http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-aarch64-linux-gnu.tar.xz
        tar -xf clang+llvm-3.8.0-aarch64-linux-gnu.tar.xz -C $SNAPCRAFT_STAGE
    build-packages: [wget]
  phantomjs:
    after: [clang]
    plugin: python
    source: https://github.com/ariya/phantomjs.git
    source-type: git
    source-tag: 2.1.1
    prepare: |
        git submodule init
        git submodule update
    build: |
        cd src
        export PHANTOMJSDIR=$(pwd)

        # prepare apt to download sources
        # sudo sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list
        # sudo apt-get update

        # download and install openssl
        # apt-get source openssl
        # cd openssl-1.0.*
        # ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib ${OPENSSL_FLAGS} linux-generic64
        # make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT depend
        # make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
        # sudo make install_sw

        # download and install icu
        # cd $PHANTOMJSDIR
        # apt-get source icu
        # cd icu-5*/source
        # ./configure --prefix=/usr --enable-static --disable-shared
        # make -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
        # sudo make install

        # build phantomjs now
        export CLANG_DIR=$SNAPCRAFT_STAGE/clang+llvm-3.8.0-aarch64-linux-gnu/bin/
        cd $PHANTOMJSDIR
        export CC=$CLANG_DIR/clang
        export CXX=$CLANG_DIR/clang++
        python build.py  --confirm --release --qt-config="-no-pkg-config" --git-clean-qtbase --git-clean-qtwebkit
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        cp $PHANTOMJSDIR/bin/phantomjs $SNAPCRAFT_PART_INSTALL/bin/phantomjs
    stage-packages:
      - build-essential
      - g++
      - flex
      - bison
      - gperf
      - ruby
      - perl
      - libsqlite3-dev
      - libfontconfig1-dev
      - libicu-dev
      - libfreetype6
      - libssl-dev 
      - libpng-dev
      - libjpeg-dev
      - python
      - libx11-dev
      - libxext-dev
      - openssl
      - icu
